### ISSUE TITLE
How to run the programme at local compute

### ISSUE THREAD

**Issue by GuoHao150** [raeslab/omixer-rpm#3]
First, I found your paper is so inspiring and I'm trying to run the `omixer-rpm-1.1.jar` with my local compute.  and my command is `java -jar omixer-rpm-1.1.jar -a demo_data/dataset.tsv -d GBMs/GBM.inputfile.txt -o test` it just return me `Annotation (demo_data/dataset.tsv) is not a valid annotation`. So How can I run this demo properly?

**Comment by omixer** [comment]
Hello, 

Could you please try running the demo with the following command?

<code>
java -jar omixer-rpm-1.1.jar -a 1 -d GBMs/GBM.inputfile.txt -i demo_data/dataset.tsv -o test
</code>

The -a option is to specify the format of the input file. For example if you are using a file with KO annotation only (e.g. https://raw.githubusercontent.com/raeslab/omixer-rpm/master/src/test/resources/matrix.tsv) you should use -a 1. If you have taxonomic information as well (e.g. https://raw.githubusercontent.com/raeslab/omixer-rpm/master/src/test/resources/taxon_matrix.tsv)
please use -a 2. 

I hope this solves your problem.

**Comment by bartns** [comment]
Hi, 

I had the same issue / error with running the example-data. 

The error message:
_ERROR - InferenceApp.main(292) | Exception while reading input. Please make sure you are using the correct annotation value (cf. --annotation description) for your input._ 

Sent me in the wrong direction towards annotation file.. However turned out my database was on the wrong format. Maybe this helps anyone.

Kind regards, 
Bart.
